### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by benjamingr** [jamietre/ioc-js#1]
jQuery promises are really different from other kinds in their behavior in versions prior to jQuery 3.0 from native or library promises.

You can use a lightweight library in the browser that is promises/A+ compliant which is a much lighter dependency than jQuery

**Comment by jamietre** [comment]
Hey Ben - good hearing from you! I actually just put this out here to show a friend I ran into at jsconf so it's not supposed to be general-purpose (yet).

Anyhoo I am no fan of jQuery "promises" - however at my job now they are pervasive in the codebase so I can't easily drop in another implementation for something that must interop with existing code, because people expect to be able to use jQuery's deferred API. But it's definitely on my hit list in the evolution of this app. I did abstract them for this thing so it doesn't actually have a jquery dependency when run on an engine with a Promise object, which is basically just for testing now but will make migration easier.

**Comment by benjamingr** [comment]
Ok then, cheers.
